// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

import Ahorcado.Horca;
import Ahorcado.Palabra;
import sun.applet.Main;

/************************************************************/
/**
 * 
 */
public class Partida {
	/**
	 * 
	 */
	public Palabra palabra;
	/**
	 * 
	 */
	public Horca horca;

	/**
	 * Muestra el estado de la horca y los resultados de palabra
	 */
	public void mostrarProgreso() {
		horca.dibujar();
		palabra.mostrarResultados();
		
	}

	/**
	 * 
	 * @return letra 
	 */
	public char pedirLetra() {
	}

	/**
	 * 
	 */
	public void resolver() {
	}

	/**
	 * 
	 * @return fin 
	 */
	public boolean comprobarFinal() {
	}
	
	public static void main(String[] args) {
		
	}
};
