// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

import Ahorcado.Horca;
import Ahorcado.Palabra;

/************************************************************/
/**
 * 
 */
public class Partida {
	/**
	 * 
	 */
	public Palabra palabra;
	/**
	 * 
	 */
	public Horca horca;

	/**
	 * 
	 */
	public void mostrarProgreso() {
	}

	/**
	 * 
	 * @return letra 
	 */
	public char pedirLetra() {
	}

	/**
	 * 
	 */
	public void resolver() {
	}

	/**
	 * 
	 * @return fin 
	 */
	public boolean comprobarFinal() {
	}
};
